name: Deploy to github pages

on:
    workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - uses: oven-sh/setup-bun@v1
  
      - name: Install depdendencies  
        run: bun install
  
      - name: Distribute
        run: bun distribute-only
  
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist