name: Deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: drademacher/not-space-invaders/.github/workflows/setup.yml

      - run: bun run build
  
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist