name: Manually deploy a version via commit SHA

on:
  workflow_dispatch:
    inputs:
      commitsha:
        description: 'SHA hash of commit'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commitsha }} 

      - uses: oven-sh/setup-bun@v1
    
      - run: bun install

      - run: bun run build
  
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist