name: Running tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1

    - name: Install depdendencies  
      run: bun install

    - name: Test
      run: bun test